import sys
import asyncio
import struct
import sqlite3
from datetime import datetime

# PyQt6 Imports
from PyQt6.QtWidgets import (
    QApplication, QMainWindow, QLabel, QVBoxLayout, QWidget, QGridLayout,
    QFrame, QHBoxLayout, QLineEdit, QPushButton, QComboBox
)
from PyQt6.QtCore import Qt, pyqtSignal, QObject, QThread
from PyQt6.QtGui import QShortcut, QKeySequence

# Bluetooth & Protobuf Imports
from bleak import BleakClient, BleakScanner
import LaunchMonitor_pb2  # This imports the file generated by protoc

# --- KONFIGURATION & UUIDs (based on https://github.com/mholow/gsp-r10-adapter/tree/main/src/bluetooth C# Source)  ---
R10_ADDRESS = "E4:7B:DD:3F:78:D7"  # Your specific device MAC

# Device Interface Service (Control/Keep-Alive)
SERVICE_UUID = "6a4e2800-667b-11e3-949a-0800200c9a66"
DEVICE_INTERFACE_NOTIFIER = "6a4e2812-667b-11e3-949a-0800200c9a66"
DEVICE_INTERFACE_WRITER = "6a4e2822-667b-11e3-949a-0800200c9a66"

# Measurement Service (Shot Data)
MEASUREMENT_SERVICE_UUID = "6a4e3400-667b-11e3-949a-0800200c9a66"
MEASUREMENT_CHAR_UUID = "6a4e3401-667b-11e3-949a-0800200c9a66" # Shot Data (Protobuf)
CONTROL_POINT_CHAR_UUID = "6a4e3402-667b-11e3-949a-0800200c9a66" # Start/Stop Radar
STATUS_CHAR_UUID = "6a4e3403-667b-11e3-949a-0800200c9a66"

# ==========================================
# DATENBANK LOGIK
# ==========================================
class ShotDatabase:
    def __init__(self, db_name="golf_data.db"):
        self.db_name = db_name
        self._init_db()

    def _init_db(self):
        with sqlite3.connect(self.db_name) as conn:
            conn.execute("""
                CREATE TABLE IF NOT EXISTS shots (
                    id INTEGER PRIMARY KEY AUTOINCREMENT,
                    timestamp DATETIME,
                    ball_speed REAL,
                    launch_angle REAL,
                    backspin REAL,
                    carry_dist REAL,
                    total_dist REAL,
                    club TEXT
                )
            """)

    def save_shot(self, m, club):
        with sqlite3.connect(self.db_name) as conn:
            conn.execute("""
                INSERT INTO shots (timestamp, ball_speed, launch_angle, backspin, carry_dist, total_dist, club)
                VALUES (?, ?, ?, ?, ?, ?, ?)
            """, (datetime.now(), m.get('ball_speed'), m.get('launch_angle'), 
                  m.get('backspin'), m.get('carry'), m.get('total'), club))

# ==========================================
# BLUETOOTH WORKER
# ==========================================
class R10Worker(QObject):
    data_received = pyqtSignal(dict)
    status_changed = pyqtSignal(str)

    def run(self):
        asyncio.run(self.main_loop())

    async def main_loop(self):
        self.status_changed.emit("connecting")
        try:
            # Auto-detect if address isn't found immediately, or use direct connect
            device = await BleakScanner.find_device_by_address(R10_ADDRESS, timeout=5.0)
            if not device:
                 # Fallback: Try to find by name if MAC fails (useful if BT cache is old)
                self.status_changed.emit("error:Device not found")
                return

            async with BleakClient(device) as client:
                self.status_changed.emit("connected")
                print(f"Connected to {client.address}")

                # 1. Enable Notifications for Shot Data
                def notification_handler(sender, data):
                    # Sender UUID helps us identify what kind of data came in
                    if sender.uuid == MEASUREMENT_CHAR_UUID:
                        self.process_shot_data(data)
                    elif sender.uuid == STATUS_CHAR_UUID:
                        print(f"Device Status: {data.hex()}")
                    elif sender.uuid == DEVICE_INTERFACE_NOTIFIER:
                        print(f"Interface Notify: {data.hex()}")

                # Subscribe to the important characteristics
                await client.start_notify(MEASUREMENT_CHAR_UUID, notification_handler)
                await client.start_notify(STATUS_CHAR_UUID, notification_handler)
                # await client.start_notify(DEVICE_INTERFACE_NOTIFIER, notification_handler)

                # 2. Initialize Device (Handshake)
                # Write 0x01 to Interface Writer (Keep-alive/Init)
                await client.write_gatt_char(DEVICE_INTERFACE_WRITER, bytearray([0x01]))
                
                # 3. Start Radar (Arm the device)
                # Write 0x01 to Control Point to start looking for balls
                await client.write_gatt_char(CONTROL_POINT_CHAR_UUID, bytearray([0x01]))
                print("R10 Radar Armed.")

                # Keep-alive Loop
                while True:
                    await asyncio.sleep(15)
                    if client.is_connected:
                        # Send Keep-Alive (standard for R10)
                        await client.write_gatt_char(DEVICE_INTERFACE_WRITER, bytearray([0x01]))
                    else:
                        break

        except Exception as e:
            print(f"Error: {e}")
            self.status_changed.emit(f"error:{str(e)}")

    def process_shot_data(self, data):
        try:
            # Parse Protobuf
            shot = LaunchMonitor_pb2.LaunchMonitor()
            shot.ParseFromString(data)
            
            # Extract fields. Note: Use .get or hasattr checks if fields are optional
            # Mapping Proto fields to our Dict
            parsed = {
                'ball_speed': round(shot.ball_speed, 1),
                'launch_angle': round(shot.launch_angle, 1),
                'backspin': int(shot.total_spin), # Proto field is total_spin
                'carry': round(shot.carry_distance, 1),
                'total': round(shot.total_distance, 1)
            }
            
            # Filter out zeroed data (sometimes R10 sends empty packets)
            if parsed['ball_speed'] > 0:
                self.data_received.emit(parsed)
                
        except Exception as e:
            print(f"Protobuf Parse Error: {e}")

# ==========================================
# GUI
# ==========================================
class GolfApp(QMainWindow):
    def __init__(self):
        super().__init__()
        self.db = ShotDatabase()
        self.current_lang = "de"
        self.translations = self._init_translations()
        self.init_ui()
        self.start_worker()
        self.retranslate_ui()

    def _init_translations(self):
        return {
            "de": {
                "window_title": "Garmin R10 Linux Monitor",
                "header_title": "R10 MONITOR",
                "club_placeholder": "Schläger eingeben...",
                "club_label": "Schläger:",
                "language_label": "Sprache:",
                "club_display": { "Driver": "Driver", "Holz 3": "Holz 3", "Eisen 7": "Eisen 7", "Eisen 9": "Eisen 9", "PW": "PW", "SW": "SW" },
                "metrics": {
                    "total": {"name": "Gesamtstrecke", "unit": "m"},
                    "carry": {"name": "Carry-Distanz", "unit": "m"},
                    "ball_speed": {"name": "Ballgeschwindigkeit", "unit": "m/s"},
                    "launch_angle": {"name": "Abflugwinkel", "unit": "°"},
                    "backspin": {"name": "Backspin", "unit": "U/min"},
                },
                "status": {
                    "initializing": "Initialisierung...",
                    "connecting": "Suche R10...",
                    "connected": "Verbunden",
                    "error": "Fehler: {}",
                    "shot_saved": "Schlag mit {} gespeichert!",
                },
            },
            "en": {
                "window_title": "Garmin R10 Linux Monitor",
                "header_title": "R10 MONITOR",
                "club_placeholder": "Enter club...",
                "club_label": "Club:",
                "language_label": "Language:",
                "club_display": { "Driver": "Driver", "Holz 3": "3 Wood", "Eisen 7": "7 Iron", "Eisen 9": "9 Iron", "PW": "PW", "SW": "SW" },
                "metrics": {
                    "total": {"name": "Total Distance", "unit": "m"},
                    "carry": {"name": "Carry Distance", "unit": "m"},
                    "ball_speed": {"name": "Ball Speed", "unit": "m/s"},
                    "launch_angle": {"name": "Launch Angle", "unit": "°"},
                    "backspin": {"name": "Backspin", "unit": "rpm"},
                },
                "status": {
                    "initializing": "Initializing...",
                    "connecting": "Searching for R10...",
                    "connected": "Connected",
                    "error": "Error: {}",
                    "shot_saved": "Shot with {} saved!",
                },
            }
        }

    def tr(self, key, *args, **kwargs):
        keys = key.split(".")
        d = self.translations[self.current_lang]
        for k in keys:
            d = d[k]
        if args or kwargs: return d.format(*args, **kwargs)
        return d

    def init_ui(self):
        self.setWindowTitle(self.tr("window_title"))
        self.setGeometry(100, 100, 1000, 750)
        self.setStyleSheet("QMainWindow { background-color: #1a1a2e; } QWidget { font-family: 'Segoe UI', Arial; }")

        central_widget = QWidget()
        self.setCentralWidget(central_widget)
        layout = QVBoxLayout(central_widget)

        # Header
        header = QHBoxLayout()
        self.title_label = QLabel(self.tr("header_title"))
        self.title_label.setStyleSheet("color: white; font-size: 28px; font-weight: bold; padding: 10px;")
        
        self.lang_combo = QComboBox()
        self.lang_combo.addItems(["Deutsch", "English"])
        self.lang_combo.currentIndexChanged.connect(self.change_language)
        self.lang_combo.setStyleSheet("background-color: #0f3460; color: white; border-radius: 10px; padding: 5px;")
        self.lang_label = QLabel(self.tr("language_label"))
        self.lang_label.setStyleSheet("color: white;")

        self.club_line_edit = QLineEdit()
        self.club_line_edit.setPlaceholderText(self.tr("club_placeholder"))
        self.club_line_edit.setStyleSheet("background-color: #0f3460; color: white; border-radius: 10px; padding: 10px; font-size: 18px;")
        self.club_line_edit.setFixedWidth(200)
        self.club_line_edit.returnPressed.connect(self.update_club_from_text)

        club_buttons_layout = QHBoxLayout()
        club_defs = [("D", "Driver"), ("3", "Holz 3"), ("7", "Eisen 7"), ("9", "Eisen 9"), ("P", "PW"), ("S", "SW")]
        self.club_buttons = []
        for key, club_name in club_defs:
            button = QPushButton()
            button.setStyleSheet("background-color: #0f3460; color: white; border-radius: 10px; padding: 5px; font-size: 16px; min-width: 80px;")
            button.clicked.connect(lambda _, c=club_name: self.set_club(c))
            club_buttons_layout.addWidget(button)
            self.club_buttons.append((button, club_name))
            shortcut = QShortcut(QKeySequence(key), self)
            shortcut.activated.connect(lambda c=club_name: self.set_club(c))

        self.club_label = QLabel(self.tr("club_label"))
        self.club_label.setStyleSheet("color: white;")

        header.addWidget(self.title_label)
        header.addStretch()
        header.addWidget(self.lang_label)
        header.addWidget(self.lang_combo)
        header.addSpacing(20)
        header.addWidget(self.club_label)
        header.addWidget(self.club_line_edit)
        header.addLayout(club_buttons_layout)
        layout.addLayout(header)

        # Metrics Grid
        self.grid_layout = QGridLayout()
        self.metric_widgets = {}
        self.cards = []
        metrics = ["total", "carry", "ball_speed", "launch_angle", "backspin"]
        colors = ["#e94560", "#0f3460", "#0f3460", "#0f3460", "#0f3460"]

        for i, (key, color) in enumerate(zip(metrics, colors)):
            card, title_label, unit_label, value_label = self.create_card(color)
            self.cards.append(card)
            self.metric_widgets[key] = { "title": title_label, "unit": unit_label, "value": value_label }
            self.grid_layout.addWidget(card, i // 2, i % 2)

        layout.addLayout(self.grid_layout)

        # Status Bar
        self.status_bar = QLabel(self.tr("status.initializing"))
        self.status_bar.setStyleSheet("color: #888; padding: 10px;")
        layout.addWidget(self.status_bar)

    def create_card(self, color):
        card = QFrame()
        card.setStyleSheet(f"background-color: #16213e; border: 2px solid {color}; border-radius: 15px;")
        l = QVBoxLayout(card)
        title = QLabel(); title.setStyleSheet("color: #888; font-size: 16px; border: none;")
        value = QLabel("0.0"); value.setStyleSheet("color: white; font-size: 48px; font-weight: bold; border: none;")
        unit = QLabel(); unit.setStyleSheet(f"color: {color}; font-size: 18px; border: none;")
        l.addWidget(title, alignment=Qt.AlignmentFlag.AlignCenter)
        l.addWidget(value, alignment=Qt.AlignmentFlag.AlignCenter)
        l.addWidget(unit, alignment=Qt.AlignmentFlag.AlignCenter)
        return card, title, unit, value

    def change_language(self, index):
        self.current_lang = "de" if index == 0 else "en"
        self.retranslate_ui()

    def retranslate_ui(self):
        self.setWindowTitle(self.tr("window_title"))
        self.title_label.setText(self.tr("header_title"))
        self.lang_label.setText(self.tr("language_label"))
        self.club_label.setText(self.tr("club_label"))
        self.club_line_edit.setPlaceholderText(self.tr("club_placeholder"))
        for button, club_name in self.club_buttons:
            button.setText(self.tr(f"club_display.{club_name}"))
        for key, widgets in self.metric_widgets.items():
            metric = self.tr(f"metrics.{key}")
            widgets["title"].setText(metric["name"])
            widgets["unit"].setText(metric["unit"])
        self.status_bar.setText(self.tr("status.initializing"))

    def set_club(self, club_name):
        self.club_line_edit.setText(club_name)
        self.current_club = club_name

    def update_club_from_text(self):
        self.current_club = self.club_line_edit.text()

    def start_worker(self):
        self.thread = QThread()
        self.worker = R10Worker()
        self.worker.moveToThread(self.thread)
        self.thread.started.connect(self.worker.run)
        self.worker.data_received.connect(self.process_shot)
        self.worker.status_changed.connect(self.handle_status)
        self.thread.start()

    def handle_status(self, code):
        if code == "connecting": self.status_bar.setText(self.tr("status.connecting"))
        elif code == "connected": self.status_bar.setText(self.tr("status.connected"))
        elif code.startswith("error:"): self.status_bar.setText(self.tr("status.error", code[6:]))
        else: self.status_bar.setText(code)

    def process_shot(self, data):
        for key, value in data.items():
            if key in self.metric_widgets:
                self.metric_widgets[key]["value"].setText(str(value))
        
        club = self.current_club if hasattr(self, 'current_club') else "Unknown"
        self.db.save_shot(data, club)
        msg = self.tr("status.shot_saved", club)
        self.status_bar.setText(msg)

if __name__ == "__main__":
    app = QApplication(sys.argv)
    window = GolfApp()
    window.show()
    sys.exit(app.exec())
